### ISSUE TITLE
When trying to run PLOT function I am getting Error: subscript contains invalid names

### ISSUE THREAD

**Issue by hollyjaro** [hsinyenwu/RiboPlotR#1]
Hello,

the RiboPlotR seems to be a great package to make some very nice looking figures.
I am trying to give it a shot but so far I am unable to produce any plots.
Once I am at the end of the pipeline with any of the PLOT functions I am getting error:

`> PLOTc("ENST00000646664.1")`
`Error: subscript contains invalid names`

I believe I followed the tutorial pretty precisely, so not sure what's the issue, I suspect the transcript naming.
To get the p_sites I successfully ran the ribotaper pipeline and with provided one-liner I created the p_sites input file.
The RNAseq bam files were created using STAR and were genome aligned and sorted.
I am using gencode annotation files, for RiboSeq it was the gencode transcriptome annotation file and for RNAseq gencode primary assembly (from the same version as transcriptome annotation used for RiboSeq).

Also, for the rna_bam.ribo function, can I just input one sample instead of 2? It's not said it it can run on one sample but I did not get any errors or warnings with that.

I would really appreciate if you could provide some short description or step by step tutorial how to make or where to get the uORF annotation file.

Thank you!
Jaro

**Comment by hsinyenwu** [comment]
Hi Jaro,

Could you please show me the gtf/gff3 for the whole ENST00000646664 gene? 

Thanks,
Larry

**Comment by hsinyenwu** [comment]
Hi Jaro,

I think I know the problem. In plants, the annotation usually follows a rule: Transcript name = Gene name + . + a number. For example, a gene is "AT1G01010" and its first isoform is "AT1G01010.1" and the second isoform is "AT1G01010.2". In the gencode annotation for human, the gene name and transcript name are unrelated. For example, the "ENST00000646664.1" is a transcript id, and the corresponding gene name is "ENSG00000075624.17". Unfortunately, the current version of RiboPlotR could only take the plant format. For now, you could modify your gtf to the plant format to fix that problem. I will add this observation to the readme file in a few days. Thanks!

Best,
Larry

**Comment by hollyjaro** [comment]
Hi Larry,

so if I want to use RiboPlotR which information should I retain in gft file? Does the order matter? As far as I know the gencode annotation has certain rules and the information is in order (by "columns"), What does RiboPlotR needs from the annotation file? I could try to modify it that way that I take transcript IDs in ensemble format "ENST00000646664" without the information following the "." (making it "gene" ID's) and leave the transcripts ID in the + . + format?

Thanks,
Jaro

**Comment by hsinyenwu** [comment]
You would need to make a gtf or gff3 with a column 9 that is similar to what we do in plants. For example, you have to make ENST00000646664 the gene_id, and ENST00000646664.1 the transcript_id. For the rows, you need those with mRNA/exon/cds in column 3. This might be a lot of work because some of genes have several completely unrelated transcript_id. It would be a lot of reformatting work for the gtf/gff3. Also I believe you would need to use the updated gtf/gff3 for RNA-seq mapping since you need the bam file for RiboPlotR.

**Comment by hollyjaro** [comment]
Hi Larry,

I see, it might be well above my coding skills, I will look for another way to visualize it.
Thanks!

Jaro

**Comment by hsinyenwu** [comment]
I will try to modify the code in the future, but may take a while so best luck with visualizing your data.
